apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd

spec:
  destination:
    # you can use cluster name like name: eks-demo or server url
    server: https://kubernetes.default.svc
    namespace: vault
  project: default
  sources:
  
  - repoURL: https://helm.releases.hashicorp.com
    chart: vault
    helm:
      valueFiles: 
      - $values/applications/vault/values.yaml
    targetRevision: 0.32.0
  - repoURL: https://github.com/Mahmoud123759/devopszen.git 
    targetRevision: HEAD
    ref: values
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/enforce-version: latest
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
